version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: splitwise
    ports:
      - '5432:5432'